Models/RequestModels/Request.cs
using TestTaskDotnet.Models.Base;

namespace TestTaskDotnet.Models.RequestModels
{
    public enum RequestType
    {
        Sale,
        Buy,
        Auction
    }

    public enum RequestStatus
    {
        Created,
        Closed,
        Cancelled
    }

    public class Request : EntityBase<int>
    {
        public string? PhoneNumber { get; set; }
        public string? FIO { get; set; }
        public string? Email { get; set; }
        public RequestType Type { get; set; }
        public RequestStatus Status { get; set; }
    }
}

Models/RequestModels/RequestHistory.cs
using TestTaskDotnet.Models.Base;

namespace TestTaskDotnet.Models.RequestModels
{
    public class RequestHistory : EntityBase<int>
    {
        public int RequestID { get; set; }
        public Request? Request { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestTaskDotnet.Models;

namespace TestTaskDotnet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RegisterForm()
        {
            return View();
        }
        public IActionResult SigIn()
        {
            return View();
        }

        public IActionResult Request()
        {
            return View();
        }
        public IActionResult RequestHistory()
        {
            return View();
        }
        public IActionResult MyRequests()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using TestTaskDotnet.Interfaces;
using TestTaskDotnet.Models.RequestModels;

namespace TestTaskDotnet.Controllers
{
    public class RequestController : Controller
    {
        private readonly ILogger<RequestController> _logger;
        private readonly IRequestService _requestService;

        public RequestController(ILogger<RequestController> logger, IRequestService requestService)
        {
            _logger = logger;
            _requestService = requestService;
        }

        public IActionResult MessagePage()
        {
            return View();
        }

        //GET

        [HttpGet]
        public IActionResult GetAllRequests()
            => Ok(_requestService.GetAllRequests());

        [HttpGet]
        public async Task<IActionResult> GetRequest(int Id)
            => Ok(await _requestService.GetRequest(Id));

        [HttpGet]
        public IActionResult GetRequestsHistory()
            => Ok(_requestService.GetRequestsHistory());


        //POST


        [HttpPost]
        public async Task<IActionResult> AddRequestToUser(int Id, string Name)
        {
            var result = await _requestService.AddRequestToUser(Id, Name);

            return result ? Ok(result) : BadRequest($"Ошибка при добавлении заявки пользователю {Name}.");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveRequestFromUser(int Id, string Name)
        {
            var result = await _requestService.RemoveRequestFromUser(Id, Name);
            return result ? Ok(result) : BadRequest($"Ошибка при удалении заявки у пользователя {Name}.");
        }

        [HttpPost]
        public async Task<IActionResult> AddRequest(string phoneNumber, string fio, string email, RequestType type)
        {
            var result = await _requestService.AddRequest(phoneNumber, fio, email, type);
            return result ? Ok(result) : BadRequest("Ошибка при создании заявки.");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveRequest(int Id)
        {
            var result = await _requestService.RemoveRequest(Id);
            return result ? Ok(result) : BadRequest("Ошибка при удалении заявки.");
        }

        [HttpPost]
        public async Task<IActionResult> CancelRequest(int Id)
        {
            var result = await _requestService.CancelRequest(Id);
            return result ? Ok(result) : BadRequest($"Заявка с ID {Id} не существует.");;
        }

        [HttpPost]
        public async Task<IActionResult> CloseRequest(int Id)
        {
            var result = await _requestService.CloseRequest(Id);
            return result ? Ok(result) : BadRequest($"Заявка с ID {Id} не существует."); ;
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TestTaskDotnet.Interfaces;

namespace TestTaskDotnet.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;

        public UserController(ILogger<UserController> logger, IUserService userService)
        {
            _logger = logger;
            _userService = userService;
        }

        //GET

        [HttpGet]
        public async Task<IActionResult> Login(string phoneNumber, string password)
        ////для вывода сообщения на страницу
        //{
        //    var result = await _userService.Login(phoneNumber, password);
        //    ViewBag.Message = result ? "Вы вошли" : "Пароль или логин введен неверно";
        //    return View();
        //}
         => Ok(await _userService.Login(phoneNumber, password) );


        [HttpGet]
        public async Task<IActionResult> GetUserRequests(string userName)
           => Ok( await _userService.GetUserRequests(userName) );


        //POST

        [HttpPost]
        public async Task<IActionResult> RegisterNewUser(string phoneNumber, string name, string password)
        {
            //для вывода сообщения на страницу
            var result = await _userService.RegisterNewUser(phoneNumber, name, password);
            //ViewBag.Message = result ? "Регистрация прошла успешно" : "Ошибка при регистрации пользователя";
            //return View();
            //если работать напрямую с запросами
            return result ? Ok("Вы успешно зарегистрировались") : BadRequest($"Ошибка при регистрации пользователя.");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать!!!</h1>
    <p>Выше указаны действия</p>
</div>

Views/Home/MyRequests.cshtml
@model TestTaskDotnet.Models.UserModels.User
<h2>Обработка заявки</h2>
<form method="post" asp-controller="Request" asp-action="AddRequestToUser">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label>ID</label><br />
        <input asp-for="Id" />
        <span asp-validation-for="Id"></span>
    </div>
    <div>
        <label>Имя пользователя</label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input type="submit" value="Присвоить заявку пользователю" />
    </div>
</form>
<form method="post" asp-controller="Request" asp-action="RemoveRequestFromUser">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label>ID</label><br />
        <input asp-for="Id" />
        <span asp-validation-for="Id"></span>
    </div>
    <div>
        <label>Имя пользователя</label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input type="submit" value="Убрать заявку у пользователя" />
    </div>
</form>

Views/Home/RegisterForm.cshtml
@model TestTaskDotnet.Models.UserModels.User
<h2>Регистрация нового пользователя</h2>
<form method="post" asp-controller="User" asp-action="RegisterNewUser">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="PhoneNumber"></label><br />
        <input asp-for="PhoneNumber" />
        <span asp-validation-for="PhoneNumber"></span>
    </div>
    <div>
        <label asp-for="Password"></label><br />
        <input asp-for="Password" />
        <span asp-validation-for="Password"></span>
    </div>
    <div>
        <input type="submit" value="Регистрация" />
    </div>
</form>

Views/Home/Request.cshtml
@model TestTaskDotnet.Models.RequestModels.Request
<h2>Обработка заявки</h2>
<form method="post" asp-controller="Request" asp-action="AddRequest">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label>Номер телефона</label><br />
        <input asp-for="PhoneNumber" />
        <span asp-validation-for="PhoneNumber"></span>
    </div>
    <div>
        <label>ФИО</label><br />
        <input asp-for="FIO" />
        <span asp-validation-for="FIO"></span>
    </div>
    <div>
        <label>Почта</label><br />
        <input asp-for="Email" />
        <span asp-validation-for="Email"></span>
    </div>
    <div>
        <label>Тип запроса</label><br />
        <input type="radio" asp-for="Type" value="0"/>Продажа
        <span asp-validation-for="Type"></span>
    </div>
    <div>
        <input type="radio" asp-for="Type" value="1"/>Покупка
        <span asp-validation-for="Type"></span>
    </div>
    <div>
        <input type="radio" asp-for="Type" value="2"/>Аукцион
        <span asp-validation-for="Type"></span>
    </div>
    <div>
        <input type="submit" value="Добавить заявку" />
    </div>
</form>
<form method="post" asp-controller="Request" asp-action="RemoveRequest">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label></label><br />
        <input asp-for="Id" />
        <span asp-validation-for="Id"></span>
    </div>
    <div>
        <input type="submit" value="Удалить заявку" />
    </div>
</form>
<form method="post" asp-controller="Request" asp-action="CancelRequest">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label></label><br />
        <input asp-for="Id" />
        <span asp-validation-for="Id"></span>
    </div>
    <div>
        <input type="submit" value="Отменить заявку" />
    </div>
</form>
<form method="post" asp-controller="Request" asp-action="CloseRequest">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label></label><br />
        <input asp-for="Id" />
        <span asp-validation-for="Id"></span>
    </div>
    <div>
        <input type="submit" value="Закрыть заявку" />
    </div>
</form>

Views/Home/RequestHistory.cshtml
@model TestTaskDotnet.Models.RequestModels.Request
<h2>Обработка заявки</h2>
<form method="get" asp-controller="Request" asp-action="GetAllRequests">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <br /><input type="submit" value="Получить все списки заявок" /><br />
    </div>
</form>
<form method="get" asp-controller="Request" asp-action="GetRequest">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label></label><br />
        <input asp-for="Id" />
        <span asp-validation-for="Id"></span>
    </div>
    <div>
        <input type="submit" value="Получить заявку" />
    </div>
</form>
<form method="get" asp-controller="Request" asp-action="GetRequestsHistory">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <br /><input type="submit" value="Получить историю заявок" />
    </div>
</form>

Views/Home/SigIn.cshtml
@model TestTaskDotnet.Models.UserModels.User
<h2>Регистрация нового пользователя</h2>
<form method="get" asp-controller="User" asp-action="Login">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="PhoneNumber"></label><br />
        <input asp-for="PhoneNumber" />
        <span asp-validation-for="PhoneNumber"></span>
    </div>
    <div>
        <label asp-for="Password"></label><br />
        <input asp-for="Password" />
        <span asp-validation-for="Password"></span>
    </div>
    <div>
        <input type="submit" value="Войти" />
    </div>
</form>